"""Index and search an extracted MediaWiki corpus through its Xapian index."""
import asyncio
import hashlib
import re
from pathlib import Path
from typing import Any

from .text_source import TextFileSource, TextFileSourceConfig, TextFilePointer
from .base import DocumentNotFoundError
from ..search import DocumentHit, SearchHit


class WikipediaSourceConfig(TextFileSourceConfig):
    xapian_directory: Path


class WikipediaPointer(TextFilePointer):
    async def get_metadata(self) -> dict[str, Any]:
        title = self.path.stem
        keywords = await asyncio.to_thread(self.source._xapian_keywords, title)
        return {
            **await super().get_metadata(),
            "title": title,
            "title_strength": 10,
            "keywords": keywords,
        }


class WikipediaSource(TextFileSource):
    source_prefix = "wikipedia"
    pointer_type = WikipediaPointer
    default_indexing_mode = "indexed"
    separate_rerank = True
    # Semantic boundaries: MediaWiki section headings. The ``== Heading ==``
    # form covers all six levels (2-6 equals signs, closing run optional).
    # HTML <h1>-<h6> headings are also valid MediaWiki markup.
    semantic_boundary_regexps = (
        rb"(?m)^={2,6}[^=\n]+?={2,6}[\t ]*$",
        rb"(?m)^</?[Hh][1-6][^>]*>.*$",
    )
    # Embedding boundaries: blank lines between paragraphs. There is no
    # finer structural boundary worth splitting on in raw wikitext.
    embedding_boundary_regexps = (rb"\n\s*\n",)

    def __init__(self, collection_id: str, *, context, collection_config, reranker=None):
        super().__init__(collection_id, context=context,
                         collection_config=collection_config, reranker=reranker)
        self.source_config = collection_config.resolve_source_config(WikipediaSourceConfig)

    async def get_document_summary(self, document_id: str) -> str:
        """Return the article's introductory lead as a plain-text summary.

        Wikipedia's lead section is written to be a standalone overview of
        the article, so the summary is extracted structurally rather than
        generated by an LLM: take the wikitext before the first section
        heading and render it to plain text (wikilinks become their display
        text, templates and markup are dropped).
        """
        pointer = self.fetch_document(document_id)
        try:
            wikitext = pointer.path.read_text(
                encoding=self.source_config.encoding,
                errors="replace",
            )
        except FileNotFoundError as exc:
            self._check_root()
            raise DocumentNotFoundError(document_id) from exc
        return await asyncio.to_thread(self._lead_summary, wikitext)

    def _lead_summary(self, wikitext: str) -> str:
        import mwparserfromhell
        from mwparserfromhell.nodes import Wikilink

        page = mwparserfromhell.parse(wikitext)
        # If the article has any section, sections[0] is the lead; if it has
        # none, sections[0] is the whole page, which is also the lead.
        sections = page.get_sections(include_lead=True, include_headings=False)
        if not sections:
            return ""
        # get_sections() returns views backed by the original parse tree, so
        # re-parse the lead before mutating it.
        lead = mwparserfromhell.parse(str(sections[0]))
        nodes = list(lead.nodes)

        # strip_code keeps the caption text of [[File:...]] / [[Image:...]]
        # links, so drop those (and any category link) before stripping.
        media_namespaces = {"file", "image", "category"}
        remove = []
        for node in nodes:
            if isinstance(node, Wikilink):
                title = str(node.title).strip()
                namespace, separator, _ = title.partition(":")
                if separator and namespace.casefold() in media_namespaces:
                    remove.append(node)
        for node in remove:
            lead.remove(node, recursive=False)

        # Render wikitext to plain text: wikilinks become their display text,
        # templates and bold/italic markup are dropped.
        text = lead.strip_code(normalize=True, collapse=True)
        # strip_code leaves magic words and does not collapse whitespace.
        text = re.sub(r"__[A-Z][A-Z0-9_]*__", "", text)
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r" ?\n ?", "\n", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        text = text.strip()
        # The lead may consist only of markup/comments; require at least one
        # word of actual prose.
        return text if re.search(r"\w", text) else ""

    def _is_included(self, path: Path) -> bool:
        return path.suffix == ".mediawiki" and super()._is_included(path)

    def _xapian_keywords(self, title: str) -> list[str]:
        import xapian

        unique_term = "Q" + (
            title if len(title) < 200 else hashlib.sha256(title.encode()).hexdigest()
        )
        try:
            database = xapian.Database(str(self.source_config.xapian_directory))
        except xapian.Error:
            return []
        try:
            postings = database.postlist(unique_term)
            try:
                posting = next(iter(postings))
            except StopIteration:
                return []
            document = database.get_document(posting.docid)
            if document.get_data().decode("utf-8") != title:
                return []
            return sorted({
                term.term.decode("utf-8")[1:]
                for term in document.termlist()
                if term.term.startswith(b"C") and len(term.term) > 1
            })
        except (UnicodeDecodeError, xapian.Error):
            return []
        finally:
            database.close()

    async def native_search(
        self, query: str, *, document_limit: int, chunk_limit: int,
    ) -> list[SearchHit]:
        if not query.strip() or document_limit <= 0:
            return []
        return await asyncio.to_thread(self._native_search, query, document_limit)

    def _native_search(self, query: str, document_limit: int) -> list[SearchHit]:
        import xapian

        database = xapian.Database(str(self.source_config.xapian_directory))
        try:
            parser = xapian.QueryParser()
            parser.set_database(database)
            parser.set_stemmer(xapian.Stem("english"))
            parser.set_stemming_strategy(parser.STEM_SOME)
            parser.set_default_op(xapian.Query.OP_OR)
            parser.add_prefix("title", "T")
            parser.add_prefix("cat", "C")
            enquiry = xapian.Enquire(database)
            enquiry.set_query(parser.parse_query(
                query, parser.FLAG_DEFAULT | parser.FLAG_BOOLEAN_ANY_CASE,
            ))
            hits = []
            seen = set()
            # Bound filtering work even if an index contains excluded/bad entries.
            offset = 0
            budget = max(100, document_limit * 10)
            while len(hits) < document_limit and offset < budget:
                matches = enquiry.get_mset(offset, min(document_limit, budget - offset))
                if not matches:
                    break
                offset += len(matches)
                for match in matches:
                    try:
                        stem = match.document.get_data().decode("utf-8")
                        if not stem or "/" in stem or "\x00" in stem:
                            continue
                        path = Path(stem + ".mediawiki")
                        if not self._is_included(path):
                            continue
                        document_id = self.encode_document_path(path.as_posix())
                        if document_id not in seen:
                            seen.add(document_id)
                            hits.append(DocumentHit(document_id, match.weight))
                    except UnicodeDecodeError:
                        continue
                    if len(hits) == document_limit:
                        break
            return hits
        finally:
            database.close()
